@endpoint=http://localhost:4000/api

### signin
POST {{endpoint}}/auth/signin
Content-Type: application/json

{
  "email": "test@test.fr",
  "password": "12341234"
}

### signup
POST {{endpoint}}/auth/signup
Content-Type: application/json

{
  "email": "test@test.fr",
  "password": "12341234",
  "passwordConfirm": "12341234",
  "firstname":"dfgdfg" ,
  "lastname": "dfgdfg",
  "birthdate": "1992-01-26",
  "address": "dfgdfg",
  "zipcode": "dgdfg",
  "city":"dfgdg",
  "country": "dgdfg"
}

### signout
GET {{endpoint}}/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEB0ZXN0LmZyIiwiZmlyc3RuYW1lIjoiZGZnZGZnIiwibGFzdG5hbWUiOiJkZmdkZmciLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNzQ4MDgwMSwiZXhwIjoxNzA4MDg1NjAxfQ.j6R4p-80Mr1tczHTeemUDJivmQLhsduPTqffGku3WB0
### test admin
GET {{endpoint}}/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6InRlc3RAdGVzdC5mciIsImZpcnN0bmFtZSI6ImRmZ2RmZyIsImxhc3RuYW1lIjoiZGZnZGZnIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3NDczMjQ5LCJleHAiOjE3MDgwNzgwNDl9.tSD3nJvoqNKTfcb7gj1o7C-eCANJNTvu1_N_LwH3Lw0