@endpoint=http://localhost:4000/api

### get all User
GET {{endpoint}}/users

### get one User by id
GET {{endpoint}}/users/8

### error404 Not found
GET {{endpoint}}/users/dfgfg

### error404 Not found
DELETE {{endpoint}}/users/hg

### delete User by id (first in auth.test signup then signin then copy the token and copy it after Bearer)
DELETE {{endpoint}}/users/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6InRlc3R0QHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA3ODMzNTQ2LCJleHAiOjE3MDg0MzgzNDZ9.ZfOWlhqEEOtJSMp22905C7kO3laDtXV8iraYvcGW0PI

### error404 Not found for connected user
DELETE {{endpoint}}/users/10000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJlbWFpbCI6InRlc3R0QHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA3ODI2ODEzLCJleHAiOjE3MDg0MzE2MTN9.U5oU25gi3ljzqVnHpBnjqe4Efc-4rh0z9ZqF-1JvkTY

### update User for connected user
PATCH {{endpoint}}/users/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6InRlc3R0QHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA3ODMzOTQxLCJleHAiOjE3MDg0Mzg3NDF9.40EaH9Z7tCbqDr4UEEjW9p2SZE5WgXGITDLnMCpIle8
Content-Type: application/json

{
  "email": "patch@patch.fr",
  "address":"patchedadress",
  "firstname":"patchedname"
}

### get one user with likes for connected user
get {{endpoint}}/users/13/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJlbWFpbCI6InRlc3R0QHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA3ODI2ODEzLCJleHAiOjE3MDg0MzE2MTN9.U5oU25gi3ljzqVnHpBnjqe4Efc-4rh0z9ZqF-1JvkTY