@endpoint=http://localhost:4000/api
@token=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJlbWFpbCI6InRlc3R0QHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA3OTE0MDk0LCJleHAiOjE3MDg1MTg4OTR9.POwO4h1zo9TMrLcsr96HlirqLEUuU_3xXlMYoe4meuI
### get all User
GET {{endpoint}}/users

### get one User by id
GET {{endpoint}}/users/8

### error404 Not found
GET {{endpoint}}/users/dfgfg

### error401 User not connected try to delete user
DELETE {{endpoint}}/users/1

### delete User by id (first in auth.test signup then signin then copy the token and copy it after Bearer)
DELETE {{endpoint}}/users/1
{{token}}

### error404 Not found for connected user
DELETE {{endpoint}}/users/10000
{{token}}

### update User for connected user
PATCH {{endpoint}}/users/11
{{token}}
Content-Type: application/json

{
  "email": "patch@patch.fr",
  "address":"patchedadress",
  "firstname":"patchedname"
}

### get one user with likes for connected user
get {{endpoint}}/users/13/likes
{{token}}