@endpoint=http://localhost:4000/api/admin

### signin
POST {{endpoint}}/auth/signin
Content-Type: application/json

{
  "email": "admin@test.fr",
  "password": "12341234"
}

### signup
POST {{endpoint}}/auth/signup
Content-Type: application/json

{
  "email": "admin@test.fr",
  "password": "12341234",
  "passwordConfirm": "12341234",
  "firstname": "dfgdfg",
  "lastname": "dfgdfg",
  "birthdate": "1992-01-26",
  "address": "dfgdfg",
  "zipcode": "dgdfg",
  "city": "dfgdg",
  "country": "dgdfg",
  "role": "admin"
}

### signout
GET {{endpoint}}/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6ImFkbWluQHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwNzgyNTkyNCwiZXhwIjoxNzA4NDMwNzI0fQ.HFt-fMJ_y78BGuSnKxhPgZmsgItjHiN-pXEbiQRUGMo
