@endpoint=http://localhost:4000/api/admin
@token=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6ImFkbWluQHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwNzgyNTkyNCwiZXhwIjoxNzA4NDMwNzI0fQ.HFt-fMJ_y78BGuSnKxhPgZmsgItjHiN-pXEbiQRUGMo


### Get All artists
GET {{endpoint}}/artists
{{token}}

### Add one albumartist
POST {{endpoint}}/artists
{{token}}
Content-Type: application/json

{
  "firstname": "albert",
  "lastname": "einstein",
  "nickname": "alberito",
  "year": "1879",
  "city":"wurtemberg" ,
  "country":"allemagne" ,
  "description": "Lorem ipsum dolor sit amet. Est delectus autem et ipsum ipsa rem corrupti totam vel quas molestiae et rerum suscipit. Ut quia vitae sed porro sunt sit vero repudiandae vel corrupti quis hic obcaecati fugit.",
  "function":"guitariste" ,
  "url_image": "http://image.net"
}


### Get one artist
GET {{endpoint}}/artists/13
{{token}}

### Modify one artist
PATCH {{endpoint}}/artists/13
{{token}}
Content-Type: application/json

{
  "nickname": "space_cake",
  "country": "autriche"
}

### Delete one album
DELETE {{endpoint}}/albums/11
{{token}}

### Error token
GET {{endpoint}}/albums




### signout
GET {{endpoint}}/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6ImFkbWluQHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwNzgyNTkyNCwiZXhwIjoxNzA4NDMwNzI0fQ.HFt-fMJ_y78BGuSnKxhPgZmsgItjHiN-pXEbiQRUGMo
