@endpoint=http://localhost:4000/api/admin
@token=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6ImFkbWluQHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwNzgyNTkyNCwiZXhwIjoxNzA4NDMwNzI0fQ.HFt-fMJ_y78BGuSnKxhPgZmsgItjHiN-pXEbiQRUGMo


### Get All events
GET {{endpoint}}/events
{{token}}

### Add one event
POST {{endpoint}}/events
{{token}}
Content-Type: application/json

{
  "name": "dubFolie ",
  "type": "concert",
  "description": "Lorem ipsum dolor sit amet. Est delectus autem et ipsum ",
  "starting_date": "2024-06-30T22:00:00.000Z",
  "ending_date":"2024-07-02T22:00:00.000Z" ,
  "city":"Paris" ,
  "country": "france",
  "location":"folies bergere" ,
  "url_image": "http://image.net"
}


### Get one event
GET {{endpoint}}/events/16
{{token}}

### Modify one event
PATCH {{endpoint}}/events/13
{{token}}
Content-Type: application/json

{
  "type": "pogo",
  "country": "autriche"
}

### Delete one event
DELETE {{endpoint}}/events/11
{{token}}

### Error token
GET {{endpoint}}/albums




### signout
GET {{endpoint}}/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6ImFkbWluQHRlc3QuZnIiLCJmaXJzdG5hbWUiOiJkZmdkZmciLCJsYXN0bmFtZSI6ImRmZ2RmZyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwNzgyNTkyNCwiZXhwIjoxNzA4NDMwNzI0fQ.HFt-fMJ_y78BGuSnKxhPgZmsgItjHiN-pXEbiQRUGMo
